### ISSUE TITLE
Authentication works using sessionStorage

### ISSUE THREAD

**Issue by atkawa7** [Seedstars/django-react-redux-base#33]
If you set the token using 

`sessionStorage.setItem('token', 'blahblah')`

 It works fine and you can access the protected  content. Could there be something wrong?

**Comment by DFilipeS** [comment]
Sorry for the late response. It is actually working as intended.

When a user logs in, the token goes to the reducer to be put in the Redux store and it is saved in the `sessionStorage`. When changing for `sessionStorage.setItem('token', 'blahblah')`, the correct token is still stored in the Redux store and when a REST request is made, the authentication uses the correct token (from the Redux store). If you clean your browser cache and try to force the Redux store to be initialized by dispatching the login with the incorrect token stored in the `sessionStorage` it won't be able to authenticate (because the token is invalid). The code below illustrates this authentication.

```const token = sessionStorage.getItem('token');
let user = {};
try {
  user = JSON.parse(sessionStorage.getItem('user'));
} catch (e) {
  // Failed to parse
}

if (token !== null) {
    store.dispatch(authLoginUserSuccess(token, user));
}```
