### ISSUE TITLE
Why use arrays as object keys in your reducer?

### ISSUE THREAD

**Issue by rclmenezes** [Seedstars/django-react-redux-base#36]
Hi,

Thanks for making this project. It's been a good learning experience for me to read through it.

However, I've been reading your reducer code and I've been scratching my head a little bit. Why use [arrays as object keys in your reducers](https://github.com/Seedstars/django-react-redux-base/blob/master/src/static/reducers/auth.js#L19)?

```javascript
export default createReducer(initialState, {
    [AUTH_LOGIN_USER_REQUEST]: (state, payload) => {
        return Object.assign({}, state, {
            isAuthenticating: true,
            statusText: null
        });
    },
    ...
```

Is there some benefit to doing this that I don't understand?

Thanks!

P.S. Wouldn't it be better for createReducer() to raise an error when it can't find the right reducer? [Right now, it'll silently fail and return the initial state](https://github.com/Seedstars/django-react-redux-base/blob/master/src/static/utils/index.js#L7).

**Comment by lfrodrigues** [comment]
You could also do 
```javascript
export default createReducer(initialState, {
    'AUTH_LOGIN_USER_REQUEST': (state, payload) => {
        return Object.assign({}, state, {
            isAuthenticating: true,
            statusText: null
        });
    },
    ...
```

But since we want to import variables from constants.js the only way to be able to use in a switch is this. If not it is considered as text and not an imported variable. 

For the second question, looking at it now I think you are correct. I honestly don't remember why I did it like this, let me think a bit about it and revert :)

**Comment by rclmenezes** [comment]
Ah! That makes sense. Normally I use a plain ol' switch. Thanks!

**Comment by fgarci03** [comment]
Hi @rclmenezes!

The array like expression is a new ES6 feature, in order to [use variables (computed names) as object keys](http://es6-features.org/#ComputedPropertyNames).

As for the state not raising an error:
Per the [redux docs](http://redux.js.org/docs/api/combineReducers.html#notes):
> For any action that is not recognized, it must return the state given to it as the first argument.

This is because, with split reducers, the store sends the action down the chain and any reducer that knows how to handle it just does it's thing, while the others ignore it. If you place a console.log on the createReducer function, you will see that it is runs twice for each action dispatched, and basically it ignores it when the action is not recognized. Maybe [this link](http://redux.js.org/docs/recipes/reducers/UsingCombineReducers.html#core-concepts) can shed a little more light on this (this being addressed in the 3rd item in the core concepts list).

Also, we are not using a switch, so that we don't have a createReducers function for each reducers file. We have a single function that handles all of them. Just that. :slightly_smiling_face:

**Comment by rclmenezes** [comment]
Thanks, @fgarci03 !
