### ISSUE TITLE
Error installing fixture

### ISSUE THREAD

**Issue by anweiss** [Seedstars/django-react-redux-base#71]
When the `backend` service spins up, it errors out as follows:

```
django.core.serializers.base.DeserializationError: Problem installing fixture '/django/src/fixtures.json': User has no field named 'username'
```

This looks to prevent the default user from being added which prevents me from logging in to the protected area.

**Comment by bernardojedi** [comment]
Same error here, it seems that the User model was changed and the file "fixtures.json" was not updated.

I was able to make it work by changing the following lines on "fixtures.json":

`"username": "admin",`
to
```
"first_name": "admin",
"date_updated": "2015-12-29T00:57:23.201Z",
```

The reason why I included the "date_updated" is because I got an error on this field after fixing the error above, which is weird because it is an "auto_now=True" field.

**Comment by lfrodrigues** [comment]
Fixed in master. Thanks for the report!
